name: Europe Code Week
markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
paginate: 5
paginate_path: "/news/page:num/"

contact:
    email: info@codeweek.eu
    twitter: CodeWeekEU
    facebook: codeEU
    github: codeeu

country-list: [austria, belgium, bulgaria, china, croatia, cyprus, czech_republic, denmark, estonia, finland, france, germany, greece, hungary, ireland, italy, kosovo, latvia, lithuania, luxembourg, malta, netherlands, poland, portugal, romania, slovakia, slovenia, spain, sweden, switzerland, united_kingdom]

country-list-2014: [austria, belarus, belgium, bulgaria, china, croatia, cyprus, czech_republic, denmark, estonia, finland, france, germany, greece, hungary, iceland, ireland, isle_of_man, italy, kosovo, latvia, lithuania, luxembourg, malta, moldova, netherlands, norway, poland, portugal, romania, serbia, slovakia, slovenia, spain, sweden, switzerland, turkey, ukraine, united_kingdom]

description: A week to celebrate coding in Europe
url: http://codeweek.eu
